fix problems
YaRomanovIvan/java-filmorate pull request #2
Opened 2023-04-03 12:33 UTC by YaRomanovIvan

В общем откатиться получилось только полностью все удалив и заново запросив репозиторий от практикума. Новый репозиторий валился на тестах проверки файлов, там видимо какая то защита от "изменений". В общем только так можно было сделать "чисто и красиво"

2023-04-03 13:28 UTC, YaRomanovIvan commented
С прошлого ревью ты меня попросил либо создать новый репозиторий, либо откатить старый.
Старый я благополучно поломал, новый не проходил тесты ругаясь на какие-то бинарные файлы.
В общем в борьбе за право сдать работу, я удалил старый и новый репозитории, запросил у практикума нулевой и попробовал все сделать тут. Однако меня ждало разочарование, потому что я ловил такую же ошибку. Пришлось разбираться =/
первые семь коммитов можно не смотреть, я там боролся за право проходить тесты, в 8-ом комите понял что именно не так, в 9 уже пройденные тесты. Собственно, теперь я и правда стал умнее в плане работы с гитом и борьбой с тестами :D
Учел замечания, напомню что там было:
1. Ошибки надо логировать не фразой "тут ошибка", а писать туда, собственно, что именно произошло
2. Убрал всякие sout
3. В pom.xml версии вынести в properties. Этот момент, надеюсь, правильно понял.

2023-04-04 07:03 UTC, krylov-sergey-sergeevich requested changes
Привет, поздравляю с успехом в твоей борьбе =)

- Логи на англ переведем давай все + логи должны давать информацию о том с кем что произошло, а не просто факт происходящего


Давай поправим мелочи и будет зачет =)

2023-04-04 07:03 UTC, krylov-sergey-sergeevich commented on HELP.md
> +# Read Me First
Файл можно удалить из проекта, он бесполезный

2023-04-04 07:03 UTC, krylov-sergey-sergeevich commented on pom.xml
> +		<java.version>11</java.version>
Все верно

2023-04-04 07:03 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Фильм обновлен!");
какой фильм?

2023-04-04 07:03 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error(exception.getMessage());
обычно не имеет смысла так делать тк исключение же само напишет в логи еще

2023-04-04 13:56 UTC, YaRomanovIvan commented
Поправил логи.
Немного непривычно, что ошибки логируются неявно, в этом плане хочется придерживаться принципа "явное лучше неявного" =)

2023-04-05 05:05 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет!

2023-04-06 16:20 UTC, merged